//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektIndywidualny.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektIndywidualny.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon alert_icon {
            get {
                object obj = ResourceManager.GetObject("alert_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert_image {
            get {
                object obj = ResourceManager.GetObject("alert_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   | c3 | c10 | c25 | c50 | c75 | c90 | c97
        ///3 | 91 | 93 | 95 | 98 | 100 | 102 | 105 
        ///4 | 97 | 99 | 102 | 105 | 108 | 110 | 113
        ///5 | 103 | 106 | 109 | 112 | 115 | 117 | 120
        ///6 | 109 | 112 | 115 | 118 | 122 | 125 | 128
        ///7 | 115 | 118 | 121 | 125 | 128 | 131 | 135
        ///8 | 120 | 123 | 127 | 131 | 134 | 138 | 141
        ///9 | 125 | 128 | 132 | 136 | 140 | 144 | 147
        ///10	| 129 | 133 | 137 | 141 | 146 | 150 | 154
        ///11	| 134 | 138 | 142 | 147 | 151 | 156 | 160
        ///12	| 139 | 143 | 148 | 153 | 158 | 163 | 167
        ///13	| 145 | 150 | 155 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultBoyHeightGrowthChart {
            get {
                return ResourceManager.GetString("DefaultBoyHeightGrowthChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   | c3 | c10 | c25 | c50 | c75 | c90 | c97
        ///3 | 12 | 13 | 14 | 15 | 16 | 18 | 20 
        ///4 | 14 | 15 | 16 | 17 | 19 | 21 | 23
        ///5 | 15 | 16 | 17 | 19 | 21 | 23 | 27
        ///6 | 17 | 18 | 20 | 22 | 24 | 28 | 32
        ///7 | 19 | 20 | 22 | 24 | 28 | 32 | 37
        ///8 | 21 | 22 | 25 | 28 | 32 | 37 | 44
        ///9 | 23 | 25 | 27 | 31 | 36 | 41 | 50
        ///10	| 25 | 27 | 30 | 34 | 40 | 47 | 56
        ///11	| 27 | 30 | 33 | 38 | 45 | 52 | 63
        ///12	| 30 | 33 | 37 | 43 | 50 | 58 | 70
        ///13	| 33 | 37 | 42 | 48 | 56 | 65 | 77
        ///14	| 38 | 42 | 47 | 54 | 62 | 71 | 83
        ///15	| 4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultBoyWeightGrowthChart {
            get {
                return ResourceManager.GetString("DefaultBoyWeightGrowthChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     | c3  | c10 | c25 | c50 | c75 | c90 | c97
        ///3   | 89  | 92  | 94  | 97  | 99 | 101 | 104 
        ///4   | 96  | 98  | 101 | 104 | 106 | 109 | 111
        ///5   | 102 | 105 | 107 | 111 | 114 | 116 | 119
        ///6   | 108 | 111 | 114 | 117 | 120 | 124 | 127
        ///7   | 113 | 116 | 120 | 123 | 127 | 130 | 133
        ///8   | 118 | 122 | 125 | 130 | 133 | 137 | 140
        ///9   | 124 | 127 | 131 | 135 | 140 | 143 | 147
        ///10	| 128 | 132 | 136 | 141 | 145 | 149 | 153
        ///11	| 134 | 139 | 142 | 147 | 152 | 157 | 160
        ///12	| 141 | 145 | 149 | 154 | 158 | 162 | 167 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultGirlHeightGrowthChart {
            get {
                return ResourceManager.GetString("DefaultGirlHeightGrowthChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   | c3 | c10 | c25 | c50 | c75 | c90 | c97
        ///3 | 12 | 13 | 13 | 15 | 16 | 17 | 19 
        ///4 | 13 | 14 | 15 | 17 | 18 | 20 | 23
        ///5 | 15 | 16 | 17 | 19 | 21 | 23 | 27
        ///6 | 16 | 17 | 19 | 21 | 24 | 27 | 31
        ///7 | 18 | 19 | 21 | 23 | 27 | 30 | 35
        ///8 | 20 | 21 | 23 | 27 | 30 | 35 | 41
        ///9 | 22 | 24 | 26 | 30 | 34 | 40 | 47
        ///10	| 24 | 26 | 29 | 33 | 39 | 45 | 53
        ///11	| 27 | 30 | 33 | 38 | 44 | 51 | 60
        ///12	| 30 | 33 | 37 | 43 | 50 | 57 | 67
        ///13	| 34 | 38 | 42 | 47 | 54 | 62 | 72
        ///14	| 38 | 42 | 46 | 51 | 58 | 65 | 74
        ///15	| 4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultGirlWeightGrowthChart {
            get {
                return ResourceManager.GetString("DefaultGirlWeightGrowthChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap female_gender_icon {
            get {
                object obj = ResourceManager.GetObject("female_gender_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon main_icon {
            get {
                object obj = ResourceManager.GetObject("main_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap male_gender_icon {
            get {
                object obj = ResourceManager.GetObject("male_gender_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
