//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektIndywidualny.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektIndywidualny.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wiek .
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiek powinien być liczbą z zakresu .
        /// </summary>
        public static string AgeIsNotInRange {
            get {
                return ResourceManager.GetString("AgeIsNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiek powinien rosnąć. .
        /// </summary>
        public static string AgeShouldBeIncreasing {
            get {
                return ResourceManager.GetString("AgeShouldBeIncreasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  i .
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość parametru znajduje się poniżej najniższego centylu..
        /// </summary>
        public static string BelowLowestPercentile {
            get {
                return ResourceManager.GetString("BelowLowestPercentile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiek dziecka:.
        /// </summary>
        public static string ChildAge {
            get {
                return ResourceManager.GetString("ChildAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płeć dziecka:.
        /// </summary>
        public static string ChildGender {
            get {
                return ResourceManager.GetString("ChildGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Płeć dziecka nie została wybrana..
        /// </summary>
        public static string ChildGenderIsNotChosen {
            get {
                return ResourceManager.GetString("ChildGenderIsNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wzrost dziecka:.
        /// </summary>
        public static string ChildHeight {
            get {
                return ResourceManager.GetString("ChildHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waga dziecka:.
        /// </summary>
        public static string ChildWeight {
            get {
                return ResourceManager.GetString("ChildWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domyślny.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wiek dziecka.
        /// </summary>
        public static string EnterChildAge {
            get {
                return ResourceManager.GetString("EnterChildAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wzrost dziecka.
        /// </summary>
        public static string EnterChildHeight {
            get {
                return ResourceManager.GetString("EnterChildHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wagę dziecka.
        /// </summary>
        public static string EnterChildWeight {
            get {
                return ResourceManager.GetString("EnterChildWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oszacuj wzrost i wagę dziecka.
        /// </summary>
        public static string EstimateButton {
            get {
                return ResourceManager.GetString("EstimateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przewidywany wzrost dziecka [cm].
        /// </summary>
        public static string EstimatedHeightLabel {
            get {
                return ResourceManager.GetString("EstimatedHeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przewidywana waga dziecka [kg].
        /// </summary>
        public static string EstimatedWeightLabel {
            get {
                return ResourceManager.GetString("EstimatedWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole .
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono pliku: .
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to od .
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dziewczynka.
        /// </summary>
        public static string Girl {
            get {
                return ResourceManager.GetString("Girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany .
        /// </summary>
        public static string Given {
            get {
                return ResourceManager.GetString("Given", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wzrost .
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik z danymi do siatki centylowej wzrostu:.
        /// </summary>
        public static string HeightFileLabel {
            get {
                return ResourceManager.GetString("HeightFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podano błędne dane..
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane w pliku..
        /// </summary>
        public static string IncorrectDataInFile {
            get {
                return ResourceManager.GetString("IncorrectDataInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nie jest liczbą całkowitą. .
        /// </summary>
        public static string IsNotAnInt {
            get {
                return ResourceManager.GetString("IsNotAnInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jest wymagane. .
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etykieta: .
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linia: .
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W pliku brakuje danych dla wieku..
        /// </summary>
        public static string MissingAgeData {
            get {
                return ResourceManager.GetString("MissingAgeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W pliku nie podano danych. .
        /// </summary>
        public static string MissingValueData {
            get {
                return ResourceManager.GetString("MissingValueData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość parametru znajduje się powyżej najwyższego centylu..
        /// </summary>
        public static string OverHighestPercentile {
            get {
                return ResourceManager.GetString("OverHighestPercentile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parametr: .
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości z siatek centylowych nie powinny na siebie nachodzić. .
        /// </summary>
        public static string PlotsValueShouldntOverlap {
            get {
                return ResourceManager.GetString("PlotsValueShouldntOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagane.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulator wzrostu i wagi dziecka.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  do .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości powinny być niemalejące. .
        /// </summary>
        public static string ValuesShouldBeNonDecreasing {
            get {
                return ResourceManager.GetString("ValuesShouldBeNonDecreasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartości powinny być dodatnie. .
        /// </summary>
        public static string ValuesShouldBePositive {
            get {
                return ResourceManager.GetString("ValuesShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waga .
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik z danymi do siatki centylowej wagi:.
        /// </summary>
        public static string WeightFileLabel {
            get {
                return ResourceManager.GetString("WeightFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  lat..
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
